import {
  WORK_ITEM_NAMES,
  WORK_ITEM_PROPERTY_IDS,
  UNIT_TYPES,
  WORK_ITEM_SUBTITLES
} from './constants';

export const workProperties = [
  { id: WORK_ITEM_PROPERTY_IDS.PREPARATORY, name: WORK_ITEM_NAMES.PREPARATORY_AND_DEMOLITION_WORKS, behavior: 'single', fields: [{ name: WORK_ITEM_NAMES.DURATION_EN, unit: UNIT_TYPES.HOUR, type: 'number' }] },
  { id: WORK_ITEM_PROPERTY_IDS.WIRING, name: WORK_ITEM_NAMES.ELECTRICAL_INSTALLATION_WORK, subtitle: 'switch, socket, light, connection point', behavior: 'single', fields: [{ name: WORK_ITEM_NAMES.NUMBER_OF_OUTLETS_EN, unit: UNIT_TYPES.PIECE, type: 'number' }] },
  { id: WORK_ITEM_PROPERTY_IDS.PLUMBING, name: WORK_ITEM_NAMES.PLUMBING_WORK, subtitle: 'hot, cold, waste, connection point', behavior: 'single', fields: [{ name: WORK_ITEM_NAMES.NUMBER_OF_OUTLETS_EN, unit: UNIT_TYPES.PIECE, type: 'number' }] },
  { id: WORK_ITEM_PROPERTY_IDS.BRICK_PARTITIONS, name: WORK_ITEM_NAMES.BRICK_PARTITIONS, subtitle: '75 - 175mm', fields: [{ name: WORK_ITEM_NAMES.WIDTH, unit: 'm', type: 'number' }, { name: WORK_ITEM_NAMES.HEIGHT, unit: 'm', type: 'number' }, { name: WORK_ITEM_NAMES.DOORS, unit: '+', type: 'counter' }, { name: WORK_ITEM_NAMES.WINDOWS, unit: '+', type: 'counter' }], complementaryWorks: ['Penetration coating', 'Netting', 'Penetration coating', 'Tiling under 60cm', 'Plastering', 'Penetration coating', 'Painting'], supportsDoubleComplementary: true },
  { id: WORK_ITEM_PROPERTY_IDS.BRICK_LOAD_BEARING, name: WORK_ITEM_NAMES.BRICK_LOAD_BEARING_WALL, subtitle: '200 - 450mm', fields: [{ name: WORK_ITEM_NAMES.WIDTH, unit: 'm', type: 'number' }, { name: WORK_ITEM_NAMES.HEIGHT, unit: 'm', type: 'number' }, { name: WORK_ITEM_NAMES.DOORS, unit: '+', type: 'counter' }, { name: WORK_ITEM_NAMES.WINDOWS, unit: '+', type: 'counter' }], complementaryWorks: ['Penetration coating', 'Netting', 'Penetration coating', 'Tiling under 60cm', 'Plastering', 'Penetration coating', 'Painting'], supportsDoubleComplementary: true },
  { id: WORK_ITEM_PROPERTY_IDS.PLASTERBOARDING_PARTITION, name: WORK_ITEM_NAMES.PLASTERBOARDING, subtitle: WORK_ITEM_SUBTITLES.PARTITION[0], types: ['Simple', 'Double', 'Triple'], fields: [{ name: WORK_ITEM_NAMES.WIDTH, unit: 'm', type: 'number' }, { name: WORK_ITEM_NAMES.LENGTH, unit: 'm', type: 'number' }, { name: WORK_ITEM_NAMES.DOORS, unit: '+', type: 'counter' }, { name: WORK_ITEM_NAMES.WINDOWS, unit: '+', type: 'counter' }], complementaryWorks: ['Penetration coating', 'Painting'], supportsDoubleComplementary: true },
  { id: WORK_ITEM_PROPERTY_IDS.PLASTERBOARDING_OFFSET, name: WORK_ITEM_NAMES.PLASTERBOARDING, subtitle: WORK_ITEM_SUBTITLES.OFFSET_WALL[0], types: ['Simple', 'Double'], fields: [{ name: WORK_ITEM_NAMES.WIDTH, unit: 'm', type: 'number' }, { name: WORK_ITEM_NAMES.HEIGHT, unit: 'm', type: 'number' }, { name: WORK_ITEM_NAMES.DOORS, unit: '+', type: 'counter' }, { name: WORK_ITEM_NAMES.WINDOWS, unit: '+', type: 'counter' }], complementaryWorks: ['Penetration coating', 'Painting'] },
  { id: WORK_ITEM_PROPERTY_IDS.PLASTERBOARDING_CEILING, name: WORK_ITEM_NAMES.PLASTERBOARDING, subtitle: WORK_ITEM_SUBTITLES.CEILING[0], fields: [{ name: WORK_ITEM_NAMES.WIDTH, unit: 'm', type: 'number' }, { name: WORK_ITEM_NAMES.LENGTH, unit: 'm', type: 'number' }, { name: WORK_ITEM_NAMES.DOORS, unit: '+', type: 'counter' }, { name: WORK_ITEM_NAMES.WINDOWS, unit: '+', type: 'counter' }], complementaryWorks: ['Penetration coating', 'Painting'] },
  { id: WORK_ITEM_PROPERTY_IDS.NETTING_WALL, name: WORK_ITEM_NAMES.NETTING, subtitle: WORK_ITEM_SUBTITLES.WALL[0], fields: [{ name: WORK_ITEM_NAMES.WIDTH, unit: 'm', type: 'number' }, { name: WORK_ITEM_NAMES.HEIGHT, unit: 'm', type: 'number' }, { name: WORK_ITEM_NAMES.DOORS, unit: '+', type: 'counter' }, { name: WORK_ITEM_NAMES.WINDOWS, unit: '+', type: 'counter' }], complementaryWorks: ['Penetration coating', 'Tiling under 60cm', 'Plastering', 'Penetration coating', 'Painting'] },
  { id: WORK_ITEM_PROPERTY_IDS.NETTING_CEILING, name: WORK_ITEM_NAMES.NETTING, subtitle: WORK_ITEM_SUBTITLES.CEILING[0], fields: [{ name: WORK_ITEM_NAMES.WIDTH, unit: 'm', type: 'number' }, { name: WORK_ITEM_NAMES.LENGTH, unit: 'm', type: 'number' }], complementaryWorks: ['Penetration coating', 'Plastering', 'Penetration coating', 'Painting'] },
  { id: WORK_ITEM_PROPERTY_IDS.PLASTERING_WALL, name: WORK_ITEM_NAMES.PLASTERING, subtitle: WORK_ITEM_SUBTITLES.WALL[0], fields: [{ name: WORK_ITEM_NAMES.WIDTH, unit: 'm', type: 'number' }, { name: WORK_ITEM_NAMES.HEIGHT, unit: 'm', type: 'number' }, { name: WORK_ITEM_NAMES.DOORS, unit: '+', type: 'counter' }, { name: WORK_ITEM_NAMES.WINDOWS, unit: '+', type: 'counter' }], complementaryWorks: ['Penetration coating', 'Painting'] },
  { id: WORK_ITEM_PROPERTY_IDS.PLASTERING_CEILING, name: WORK_ITEM_NAMES.PLASTERING, subtitle: WORK_ITEM_SUBTITLES.CEILING[0], fields: [{ name: WORK_ITEM_NAMES.WIDTH, unit: 'm', type: 'number' }, { name: WORK_ITEM_NAMES.LENGTH, unit: 'm', type: 'number' }], complementaryWorks: ['Penetration coating', 'Painting'] },
  { id: WORK_ITEM_PROPERTY_IDS.FACADE_PLASTERING, name: WORK_ITEM_NAMES.FACADE_PLASTERING, fields: [{ name: WORK_ITEM_NAMES.WIDTH, unit: 'm', type: 'number' }, { name: WORK_ITEM_NAMES.HEIGHT, unit: 'm', type: 'number' }, { name: WORK_ITEM_NAMES.DOORS, unit: '+', type: 'counter' }, { name: WORK_ITEM_NAMES.WINDOWS, unit: '+', type: 'counter' }] },
  { id: WORK_ITEM_PROPERTY_IDS.CORNER_BEAD, name: WORK_ITEM_NAMES.INSTALLATION_OF_CORNER_BEAD, behavior: 'single', fields: [{ name: WORK_ITEM_NAMES.LENGTH, unit: 'm', type: 'number' }] },
  { id: WORK_ITEM_PROPERTY_IDS.WINDOW_SASH, name: WORK_ITEM_NAMES.PLASTERING_OF_WINDOW_SASH, behavior: 'single', fields: [{ name: WORK_ITEM_NAMES.LENGTH, unit: 'm', type: 'number' }] },
  { id: WORK_ITEM_PROPERTY_IDS.PENETRATION_COATING, name: WORK_ITEM_NAMES.PENETRATION_COATING, fields: [{ name: WORK_ITEM_NAMES.WIDTH, unit: 'm', type: 'number' }, { name: WORK_ITEM_NAMES.HEIGHT, unit: 'm', type: 'number' }] },
  { id: WORK_ITEM_PROPERTY_IDS.PAINTING_WALL, name: WORK_ITEM_NAMES.PAINTING, subtitle: 'wall, 2 layers', fields: [{ name: WORK_ITEM_NAMES.WIDTH, unit: 'm', type: 'number' }, { name: WORK_ITEM_NAMES.HEIGHT, unit: 'm', type: 'number' }], complementaryWorks: ['Penetration coating'] },
  { id: WORK_ITEM_PROPERTY_IDS.PAINTING_CEILING, name: WORK_ITEM_NAMES.PAINTING, subtitle: 'ceiling, 2 layers', fields: [{ name: WORK_ITEM_NAMES.WIDTH, unit: 'm', type: 'number' }, { name: WORK_ITEM_NAMES.LENGTH, unit: 'm', type: 'number' }], complementaryWorks: ['Penetration coating'] },
  { id: WORK_ITEM_PROPERTY_IDS.LEVELLING, name: WORK_ITEM_NAMES.LEVELLING, fields: [{ name: WORK_ITEM_NAMES.WIDTH, unit: 'm', type: 'number' }, { name: WORK_ITEM_NAMES.LENGTH, unit: 'm', type: 'number' }], complementaryWorks: ['Penetration coating'] },
  { id: WORK_ITEM_PROPERTY_IDS.FLOATING_FLOOR, name: WORK_ITEM_NAMES.FLOATING_FLOOR, fields: [{ name: WORK_ITEM_NAMES.WIDTH, unit: 'm', type: 'number' }, { name: WORK_ITEM_NAMES.LENGTH, unit: 'm', type: 'number' }] },
  { id: WORK_ITEM_PROPERTY_IDS.TILING_UNDER_60, name: WORK_ITEM_NAMES.TILING_UNDER_60CM, subtitle: 'ceramic masculine', fields: [{ name: WORK_ITEM_NAMES.WIDTH, unit: 'm', type: 'number' }, { name: WORK_ITEM_NAMES.HEIGHT, unit: 'm', type: 'number' }, { name: WORK_ITEM_NAMES.DOORS, unit: '+', type: 'counter' }, { name: WORK_ITEM_NAMES.WINDOWS, unit: '+', type: 'counter' }], additionalFields: [{ name: WORK_ITEM_NAMES.LARGE_FORMAT, subtitle: WORK_ITEM_NAMES.ABOVE_60CM, type: 'toggle' }, { name: WORK_ITEM_NAMES.JOLLY_EDGING, unit: 'm', type: 'number' }] },
  { id: WORK_ITEM_PROPERTY_IDS.PAVING_UNDER_60, name: WORK_ITEM_NAMES.PAVING_UNDER_60CM, subtitle: 'ceramic feminine', fields: [{ name: WORK_ITEM_NAMES.WIDTH, unit: 'm', type: 'number' }, { name: WORK_ITEM_NAMES.LENGTH, unit: 'm', type: 'number' }], additionalFields: [{ name: WORK_ITEM_NAMES.LARGE_FORMAT, subtitle: WORK_ITEM_NAMES.ABOVE_60CM, type: 'toggle' }, { name: WORK_ITEM_NAMES.PLINTH, subtitle: WORK_ITEM_NAMES.CUTTING_AND_GRINDING, unit: 'm', type: 'number' }, { name: WORK_ITEM_NAMES.PLINTH, subtitle: WORK_ITEM_NAMES.BONDING, unit: 'm', type: 'number' }] },
  { id: WORK_ITEM_PROPERTY_IDS.GROUTING, name: WORK_ITEM_NAMES.GROUTING, fields: [{ name: WORK_ITEM_NAMES.WIDTH, unit: 'm', type: 'number' }, { name: WORK_ITEM_NAMES.LENGTH, unit: 'm', type: 'number' }] },
  { id: WORK_ITEM_PROPERTY_IDS.SILICONING, name: WORK_ITEM_NAMES.SILICONING, behavior: 'single', fields: [{ name: WORK_ITEM_NAMES.LENGTH, unit: 'm', type: 'number' }] },
  { id: WORK_ITEM_PROPERTY_IDS.SANITY_INSTALLATION, name: WORK_ITEM_NAMES.SANITARY_INSTALLATIONS, types: ['Corner valve', 'Standing mixer tap', 'Wall-mounted tap', 'Flush-mounted tap', 'Toilet combi', 'Concealed toilet', 'Sink', 'Sink with cabinet', 'Bathtub', 'Shower cubicle', 'Installation of gutter', 'Urinal', 'Bath screen', 'Mirror'] },
  { id: WORK_ITEM_PROPERTY_IDS.WINDOW_INSTALLATION, name: WORK_ITEM_NAMES.WINDOW_INSTALLATION, fields: [{ name: WORK_ITEM_NAMES.CIRCUMFERENCE, unit: 'm', type: 'number' }, { name: WORK_ITEM_NAMES.PRICE, unit: '€/pc', type: 'number' }] },
  { id: WORK_ITEM_PROPERTY_IDS.DOOR_JAMB_INSTALLATION, name: WORK_ITEM_NAMES.INSTALLATION_OF_DOOR_JAMB, behavior: 'single', fields: [{ name: WORK_ITEM_NAMES.COUNT, unit: 'pc', type: 'number' }, { name: WORK_ITEM_NAMES.PRICE, unit: '€/pc', type: 'number' }] },
  { id: WORK_ITEM_PROPERTY_IDS.CUSTOM_WORK, name: WORK_ITEM_NAMES.CUSTOM_WORK_AND_MATERIAL, hasTypeSelector: true, types: ['Work', 'Material'], hasUnitSelector: true, workUnits: ['bm', 'm2', 'm3', 'ks', 'bal', 'hod', 'km', 'deň'], materialUnits: ['bm', 'm2', 'm3', 'ks', 'bal', 'kg', 't', 'km'], fields: [{ name: WORK_ITEM_NAMES.NAME, unit: 'text', type: 'text' }, { name: WORK_ITEM_NAMES.QUANTITY, unit: 'number', type: 'number' }, { name: WORK_ITEM_NAMES.PRICE, unit: '€/unit', type: 'number' }] },
  { id: WORK_ITEM_PROPERTY_IDS.COMMUTE, name: WORK_ITEM_NAMES.COMMUTE, behavior: 'single', fields: [{ name: WORK_ITEM_NAMES.DISTANCE_EN, unit: UNIT_TYPES.KM, type: 'number' }, { name: WORK_ITEM_NAMES.DURATION_EN, unit: UNIT_TYPES.DAY, type: 'number' }] },
  { id: WORK_ITEM_PROPERTY_IDS.RENTALS, name: 'Rentals', items: [{ name: WORK_ITEM_NAMES.SCAFFOLDING_EN, fields: [{ name: WORK_ITEM_NAMES.LENGTH, unit: 'm', type: 'number' }, { name: WORK_ITEM_NAMES.HEIGHT, unit: 'm', type: 'number' }, { name: WORK_ITEM_NAMES.RENTAL_DURATION, unit: 'day', type: 'number' }] }, { name: WORK_ITEM_NAMES.CORE_DRILL, fields: [{ name: WORK_ITEM_NAMES.COUNT, unit: 'h', type: 'number' }] }, { name: WORK_ITEM_NAMES.TOOL_RENTAL, fields: [{ name: WORK_ITEM_NAMES.COUNT, unit: 'h', type: 'number' }] }] }
];